# https://taskfile.dev/

version: "3"

tasks:
  dbinit:
    desc: Initialize MongoDB indexes and optionally seed apps
    cmd: go run ./cmd/migrator --config=./config/local.yaml --seed

  dbinit-test:
    desc: Initialize test MongoDB database
    cmd: go run ./cmd/migrator --config=./config/test.yaml --seed

  run:
    desc: Run the SSO server
    cmd: go run ./cmd/sso

  test:
    desc: Run tests (requires MongoDB and SSO server running)
    cmd: go test -v ./tests/...

  docker-up:
    desc: Start all services with Docker Compose
    cmd: docker-compose up -d

  docker-down:
    desc: Stop all Docker Compose services
    cmd: docker-compose down
